-- 文件说明：这个 SQL 脚本负责把主键从 MySQL 自增改成雪花算法 ID。
-- 使用方式：在 MySQL Workbench 中打开本文件，确认数据库名是 oceanwiki 后执行。
-- 注意：执行后，新数据的 ID 由后端 MyBatis-Plus 雪花算法生成，不再由数据库 AUTO_INCREMENT 生成。

USE `oceanwiki`;

ALTER TABLE `category` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '分类ID';
ALTER TABLE `ebook` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '电子书ID';
ALTER TABLE `doc` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '文档ID';
ALTER TABLE `user` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '用户ID';
ALTER TABLE `sys_role` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '角色ID';
ALTER TABLE `sys_permission` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '权限ID';
ALTER TABLE `sys_user_role` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '关联ID';
ALTER TABLE `sys_role_permission` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '关联ID';
ALTER TABLE `ebook_snapshot` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '快照ID';
ALTER TABLE `user_favorite` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '收藏ID';
ALTER TABLE `reading_history` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '阅读历史ID';
ALTER TABLE `user_comment` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '评论ID';
ALTER TABLE `user_feedback` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '反馈ID';
ALTER TABLE `user_notice` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '通知ID';
ALTER TABLE `operation_log` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '日志ID';
ALTER TABLE `sensitive_word` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '敏感词ID';
ALTER TABLE `feedback_reply` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '回复ID';
ALTER TABLE `game_score` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '成绩ID';
ALTER TABLE `doc_vote` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '点赞记录ID';
ALTER TABLE `doc_version` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '版本ID';
